adding create project to role
feedhenry/buildfarm-installer pull request #7
Opened 2017-06-16 14:19 UTC by laurafitzgerald

**What**
Adding a create project task to the role. 
This task will only complete if the user does not already have a project created using the default {{ project_name }}

**Why**
As this is a dependency of a playbook the project may already be created. If it is not however it should be created.

@aliok ping for review

2017-06-16 14:25 UTC, aliok requested changes

2017-06-16 14:25 UTC, aliok commented on android-sdk/tasks/main.yml
> +  changed_when: create_project_result.rc == 0 or (android_create_result == 1 and 'created' in create_project_result.stdout)
`android_create_result` is a minor copy paste error :)

2017-06-19 08:15 UTC, laurafitzgerald commented on android-sdk/tasks/main.yml
> +  changed_when: create_project_result.rc == 0 or (android_create_result == 1 and 'created' in create_project_result.stdout)
yep will fix

2017-06-19 08:47 UTC, laurafitzgerald commented
@aliok rebased the changes into the existing commit.

2017-06-19 08:51 UTC, aliok commented
Looks good to me :)

2017-06-19 08:51 UTC, aliok approved these changes

2017-06-19 09:53 UTC, merged